########################################################
#               Built-In Integrations                  #
########################################################

## Default Config ##

hassio:
homeassistant:
    customize: !include customize.yaml
automation: !include automations.yaml
config:
frontend: !include themes.yaml
history:
input_boolean:
input_number:
input_select:
input_text:
input_datetime:
logbook:
map:
mobile_app:
person:
scene:  !include scenes.yaml
script: !include scripts.yaml
ssdp:
sun:
system_health:
zeroconf:
zone:

## Default Config ##

discovery:
# Offload to external system
#recorder: 
http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3
panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Mesh
    sidebar_icon: mdi:access-point-network
    url_path: zwave
wake_on_lan:
media_player:

########################################################
#                 Offloaded Configs                    #
########################################################

group: !include groups.yaml
camera: !include camera.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml
notify: !include notify.yaml
switch: !include switch.yaml
ios: !include ios.yaml
#homekit: !include homekit.yaml

########################################################
#               Third Party Integrations               #
########################################################

# Via GUI
# ecobee

# Add Later
# uptime
# uptimerobot
# roomba

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwavekey
  debug: false
  
webostv:
    host: 172.16.1.15
    name: Dining Room TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret TVMAC

cover:
  - platform: mqtt
    name: "Garage Door"
    command_topic: "tnt/garagedoor/set"
    state_topic: "tnt/garagedoor/state"
    availability_topic: "tnt/garagedoor/LWT"
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    state_open: "opened"
    state_closed: "closed"
    payload_available: "online"
    payload_not_available: "offline"
    device_class: "garage"
    
    