########################################################
#                   Common Config                      #
########################################################

homeassistant:
  name: !secret name
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 5
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  auth_providers:
  - type: trusted_networks
    trusted_networks:
      - 172.16.2.0/24
  - type: homeassistant
    
zone:
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    icon: mdi:briefcase
  - name: School
    latitude: !secret school_lat
    longitude: !secret school_long
    icon: mdi:bus
  - name: Base
    radius: 2000
    latitude: !secret base_lat 
    longitude: !secret base_long
    icon: mdi:shield-airplane
    
http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

history:
    include:
        domains:
            - sensor
            - switch

map:
recorder:
    purge_keep_days: 7
    
config:
hassio:
frontend: !include themes.yaml
mobile_app:
person:
sun:
system_health:
wake_on_lan:

########################################################
#                 Offloaded Configs                    #
########################################################

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml
notify: !include notify.yaml
media_player: !include media_player.yaml
switch: !include switch.yaml
ios: !include ios.yaml
homekit: !include homekit.yaml

########################################################
#                 Third Party Configs                  #
########################################################

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Mesh
    sidebar_icon: mdi:access-point-network
    url_path: zwave

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwavekey
  debug: false
  
weather:
  - platform: darksky
    api_key: !secret darksky_api
    
ecobee:
  api_key: !secret ecobee_api
  
digital_ocean:
  access_token: !secret digitalocean_api
  
# vacuum:
  # - platform: roomba
    # host: 172.16.1.132
    # username: !secret roomba_user
    # password: !secret roomba_pass
    # continuous: true
    
input_datetime:
  wake_up:
    name: Wakeup Time
    has_date: false
    has_time: true

cover:
  - platform: mqtt
    name: "Garage Door"
    command_topic: "tnt/garagedoor/set"
    state_topic: "tnt/garagedoor/state"
    availability_topic: "tnt/garagedoor/LWT"
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    state_open: "opened"
    state_closed: "closed"
    payload_available: "online"
    payload_not_available: "offline"
    device_class: "garage"